### ISSUE TITLE
A question about compiling nms

### ISSUE THREAD

**Issue by GongDianCheng** [lucastabelini/LaneATT#106]
Hi，I know your nms are compiled under Cuda10.2，it works well。

My Cuda version is 11.3 due to hardware upgrade，and an error occurred while compile。

So,I want to ask you whether need to replace some content under "lib/nms" when compiling under Cuda11

Any advice would be appreciated。

**Comment by GongDianCheng** [comment]
sorry to bother you，i find my question is the same as NMS replacement #94。I will try it

**Comment by GongDianCheng** [comment]
However，it does’nt work to me

**Comment by lucastabelini** [comment]
I have not tried to compile the NMS module with CUDA 11.3. What exactly happens when you try to compile it?

**Comment by Richard-M-chen** [comment]
Hi, i meet same question,when i try to compile it,i get this
(laneatt) daniel.chen@shaxbw07:/CV1NFS/daniel.chen/code_base/LaneATT/lib/nms$ python setup.py install
running install
running bdist_egg
running egg_info
writing src/nms.egg-info/PKG-INFO
writing dependency_links to src/nms.egg-info/dependency_links.txt
writing top-level names to src/nms.egg-info/top_level.txt
reading manifest file 'src/nms.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'nms.details' extension
/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/cuda/__init__.py:125: UserWarning: 
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(name='nms', packages=['nms'],
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 464, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 372, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/CN/daniel.chen/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1414, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.6) or GPU not supported

**Comment by lucastabelini** [comment]
You can see the problem in the output: "GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37."
