### ISSUE TITLE
about inference on my picture and how to save predict results （txt files）?

### ISSUE THREAD

**Issue by obitooooo** [lucastabelini/LaneATT#118]
1.Hello dear author, I now after modifying the yml file, with python main.py test -exp_name xxxxx_r18 to test my own image (unlabeled), it normally shows the prediction results, but when the end of all the predictions, it is reported wrong, I want to know why; 
''
2022-06-01 09:31:51.288699: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/nvidia/catkin_ws_ga/devel/lib:/opt/ros/melodic/lib:/usr/local/cuda-10.2/lib64:/home/lichunlin16/TensorRT-7.0.0.11/lib:/home/nvidia/perception_ws/src/perception/perception_alg_install/lib
2022-06-01 09:31:51.288721: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[2022-06-01 09:31:52,577] [lib.runner] [INFO] Loading model /home/lichunlin16/LaneATT/laneatt_r18_culane521/models/model_0030.pt
Looking for image files with the pattern /home/lichunlin16/LaneATT/1/**/*.jpg
[2022-06-01 09:31:53,916] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2022-06-01 09:31:53,916] [lib.datasets.lane_dataset] [INFO] Done.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.96it/s]
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 55, in main
    runner.eval(epoch=args.epoch or exp.get_last_checkpoint_epoch(), save_predictions=args.save_predictions)
  File "/home/lichunlin16/LaneATT/lib/runner.py", line 106, in eval
    self.exp.eval_end_callback(dataloader.dataset.dataset, predictions, epoch)
  File "/home/lichunlin16/LaneATT/lib/experiment.py", line 130, in eval_end_callback
    metrics = self.save_epoch_results(dataset, predictions, epoch_evaluated)
  File "/home/lichunlin16/LaneATT/lib/experiment.py", line 137, in save_epoch_results
    predictions_dir = os.path.join(epoch_results_path, '{}_predictions'.format(dataset.split))
AttributeError: 'NoLabelDataset' object has no attribute 'split'
''

2.in addition, I want to know how to use the trained model to test the picture and save the detection results, I want to get the prediction label txt file of the picture, Because I want to use this semi-automated annotation method to generate some of my own dataset for training, can you help me, thank you!

**Comment by obitooooo** [comment]
about 1st qus: I used python main.py test --exp_name  xxxxxx_r18  --view all ，it shows the predict results ，when finished ，it displayed：AttributeError: 'NoLabelDataset' object has no attribute 'split'
about 2nd qus：I need The result predicted by the model， one picture one txt label file，to create my dataset，because use labelme to label the picture is too much hard~

**Comment by obitooooo** [comment]
about 2nd qus：I used --save_predictions successfully got .pkl file 35kb，does it contain label txt message？how can i get these txt files？

**Comment by lucastabelini** [comment]
The .pkl file contains the model's raw predictions ([source](https://github.com/lucastabelini/LaneATT/blob/main/lib/runner.py#L105)).. The ` AttributeError: 'NoLabelDataset' object has no attribute 'split'` error occurred because at the end of the eval loop it tries to compute the metrics for the predictions, but it can't since `NoLabelDataset` is not really a dataset, just a wrapper to load images without annotations. At the moment there's nothing implemented in the code to produce txt files for the predictions since the implementation is geared towards research and not production.
