### ISSUE TITLE
example.yml  not find

### ISSUE THREAD

**Issue by 1429352509lyh** [lucastabelini/LaneATT#133]
Hello, I read your article, now this file example.yml is missing, is this file generated by performing install, or did you forget to upload this file example.yml

**Comment by 1429352509lyh** [comment]
(laneatt) E:\daima\LaneATT-main\LaneATT-main\lib\nms>python setup.py install
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin'
running install
running bdist_egg
running egg_info
writing src\nms.egg-info\PKG-INFO
writing dependency_links to src\nms.egg-info\dependency_links.txt
writing top-level names to src\nms.egg-info\top_level.txt
reading manifest file 'src\nms.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src\nms.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\nms
copying build\lib\nms\__init__.py -> build\bdist.win-amd64\egg\nms
byte-compiling build\bdist.win-amd64\egg\nms\__init__.py to __init__.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying src\nms.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying src\nms.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\nms.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\nms.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\nms-0.0.0-py3.8.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing nms-0.0.0-py3.8.egg
Removing c:\users\lenovo\.conda\envs\laneatt\lib\site-packages\nms-0.0.0-py3.8.egg
Copying nms-0.0.0-py3.8.egg to c:\users\lenovo\.conda\envs\laneatt\lib\site-packages
nms 0.0.0 is already the active version in easy-install.pth

Installed c:\users\lenovo\.conda\envs\laneatt\lib\site-packages\nms-0.0.0-py3.8.egg
Processing dependencies for nms==0.0.0
Finished processing dependencies for nms==0.0.0

(laneatt) E:\daima\LaneATT-main\LaneATT-main\lib\nms>cd E:\daima\LaneATT-main\LaneATT-main

(laneatt) E:\daima\LaneATT-main\LaneATT-main>
(laneatt) E:\daima\LaneATT-main\LaneATT-main>python main.py train --exp_name example --cfg example.yml
**Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 48, in main
    cfg = Config(cfg_path)
  File "E:\daima\LaneATT-main\LaneATT-main\lib\config.py", line 11, in __init__
    self.load(config_path)
  File "E:\daima\LaneATT-main\LaneATT-main\lib\config.py", line 14, in load
    with open(path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'example.yml'**
