### ISSUE TITLE
change np.float

### ISSUE THREAD

**Issue by byungjinku** [lucastabelini/LaneATT#137]
HI 
where I have to change for 'float' ?
here the error message

(laneatt) bjku@bjku:~/LaneATT$ python main.py train --exp_name laneatt_r34_tusimple --cfg cfgs/laneatt_tusimple_resnet34.yml
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from lib.config import Config
  File "/home/bjku/LaneATT/lib/config.py", line 4, in <module>
    import lib.datasets as datasets
  File "/home/bjku/LaneATT/lib/datasets/__init__.py", line 1, in <module>
    from .lane_dataset import LaneDataset
  File "/home/bjku/LaneATT/lib/datasets/lane_dataset.py", line 15, in <module>
    from .tusimple import TuSimple
  File "/home/bjku/LaneATT/lib/datasets/tusimple.py", line 8, in <module>
    from utils.tusimple_metric import LaneEval
  File "/home/bjku/LaneATT/utils/tusimple_metric.py", line 4, in <module>
    from sklearn.linear_model import LinearRegression
  File "/home/bjku/miniconda3/envs/laneatt/lib/python3.8/site-packages/sklearn/linear_model/__init__.py", line 11, in <module>
    from ._least_angle import (Lars, LassoLars, lars_path, lars_path_gram, LarsCV,
  File "/home/bjku/miniconda3/envs/laneatt/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py", line 34, in <module>
    method='lar', copy_X=True, eps=np.finfo(np.float).eps,
  File "/home/bjku/miniconda3/envs/laneatt/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by Aayushktyagi** [comment]
pip install numpy==1.19 helps here.
