### ISSUE TITLE
RuntimeError: data/culane_anchors_freq.pt is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by jajajajaja121** [lucastabelini/LaneATT#14]
When I test model, this error appeared, this is my command:
`python main.py test --exp_name laneatt_r18_culane/`
I have not change anything, except my pytorch version is 1.2. I don't know why this error appeared, and the whole outputs are below:

```
Traceback (most recent call last):
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: '16791808'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 1095, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 1037, in frombuf
    chksum = nti(buf[148:156])
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 189, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/la/lib/python3.7/site-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/opt/conda/envs/la/lib/python3.7/site-packages/torch/serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/opt/conda/envs/la/lib/python3.7/tarfile.py", line 2301, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 55, in main
    runner.eval(epoch=args.epoch or exp.get_last_checkpoint_epoch(), save_predictions=args.save_predictions)
  File "/home/xiongpan/code/LaneATT/lib/runner.py", line 76, in eval
    model = self.cfg.get_model()
  File "/home/xiongpan/code/LaneATT/lib/config.py", line 28, in get_model
    return getattr(models, name)(**parameters, **kwargs)
  File "/home/xiongpan/code/LaneATT/lib/models/laneatt.py", line 51, in __init__
    anchors_mask = torch.load(anchors_freq_path).cpu()
  File "/opt/conda/envs/la/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/la/lib/python3.7/site-packages/torch/serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: data/culane_anchors_freq.pt is a zip archive (did you mean to use torch.jit.load()?)
```

**Comment by xinosaurous** [comment]
Hi, did you resolve this issue? I know it is a model format incompatibility between pytorch 1.6 and earlier pytorch versions, but I do not know how to convert the format.

**Comment by jajajajaja121** [comment]
> Hi, did you resolve this issue? I know it is a model format incompatibility between pytorch 1.6 and earlier pytorch versions, but I do not know how to convert the format.

I don't know how to solve it, Maybe you can try to use the source code in pytorch1.6, which load the model, load it in this way, and save the weights in lower version.
