### ISSUE TITLE
'Module' Object is not callable

### ISSUE THREAD

**Issue by hamza-riazee** [lucastabelini/LaneATT#18]
I am trying to train the model according to the instruction given in the readme but I am getting this error can you tell me whats wrong.

**Comment by lucastabelini** [comment]
I need more information.

**Comment by hamza-riazee** [comment]
Brother How can I change the training and testing from cuda to cpu

**Comment by lucastabelini** [comment]
With this implementation, you can't. The NMS procedure is implemented only for CUDA.

**Comment by hamza-riazee** [comment]
ok thanks for letting me know

**Comment by zdminging** [comment]
大佬您好 我也遇到了同样的问题
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 52, in main
    runner.train()
  File "/mnt/zdm/LaneATT-main/lib/runner.py", line 51, in train
    outputs = model(images, **self.cfg.get_train_parameters())
  File "/mnt/obj_detect_env/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/zdm/LaneATT-main/lib/models/laneatt.py", line 108, in forward
    proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold)
  File "/mnt/zdm/LaneATT-main/lib/models/laneatt.py", line 129, in nms
    keep, num_to_keep, _ = nms(proposals, scores, overlap=nms_thres, top_k=nms_topk)
TypeError: 'module' object is not callable

显示的错误如上，请问您有啥解决方法吗~？谢谢啦
