### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/laneatt_r34_tusimple/config.yaml'

### ISSUE THREAD

**Issue by edwardchang0112** [lucastabelini/LaneATT#62]
After running
```
python3 main.py test --exp_name laneatt_r34_tusimple
```
shows the error
```
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/laneatt_r34_tusimple/config.yaml'
```
Anyone got this error message? Please share some comments with me!

**Comment by thanhnv57** [comment]
You must train before test. 
In case, you just want to test, you can train cmd once.
Then stop it, place pretrained model into `experiments/laneatt_r34_tusimple/models` then run your test cmd.

**Comment by edwardchang0112** [comment]
@thanhnv57 
Thanks for the reply!
Then I run
```
python3 main.py train --exp_name laneatt_r34_tusimple --cfg cfgs/laneatt_tusimple_resnet34.yml
```
got the error
```
2021-06-26 20:01:23.719196: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 52, in main
    runner.train()
  File "/home/fiduciaedge-nx/Desktop/LaneATT-main/lib/runner.py", line 32, in train
    model = self.cfg.get_model()
  File "/home/fiduciaedge-nx/Desktop/LaneATT-main/lib/config.py", line 28, in get_model
    return getattr(models, name)(**parameters, **kwargs)
  File "/home/fiduciaedge-nx/Desktop/LaneATT-main/lib/models/laneatt.py", line 29, in __init__
    self.feature_extractor, backbone_nb_channels, self.stride = get_backbone(backbone, pretrained_backbone)
  File "/home/fiduciaedge-nx/Desktop/LaneATT-main/lib/models/laneatt.py", line 386, in get_backbone
    backbone = torch.nn.Sequential(*list(resnet34(pretrained=pretrained).children())[:-2])
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 289, in resnet34
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 263, in _resnet
    progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile
```
Any comments on this?

**Comment by thanhnv57** [comment]
Did you use exactly package and python version as in requirement.txt?

**Comment by ok-kewei** [comment]
@lucastabelini  can i confirm that there's no pretrained model given that we have to train from scratch by our own ? Thanks.

**Comment by lucastabelini** [comment]
There's a link for the pretrained models on the README.md.
