### ISSUE TITLE
NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by wangnian97** [lucastabelini/LaneATT#80]
i am training on culane , how can i do 

[2021-10-26 20:00:01,266] [lib.datasets.culane] [INFO] Loading CULane annotations (cached)...
[2021-10-26 20:00:10,368] [lib.datasets.culane] [INFO] 88880 annotations loaded, with a maximum of 4 lanes in an image.
[2021-10-26 20:00:10,369] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2021-10-26 20:02:25,370] [lib.datasets.lane_dataset] [INFO] Done.
  0%|                                                    | 0/15 [00:00<?, ?it/s]
  0%|                                                 | 0/11110 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/disk/wangnian/LaneATT/main.py", line 52, in main
    runner.train()
  File "/home/disk/wangnian/LaneATT/lib/runner.py", line 45, in train
    for i, (images, labels, _) in enumerate(pbar):
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/tqdm/std.py", line 1108, in __iter__
    for obj in iterable:
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/disk/wangnian/anaconda3/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/disk/wangnian/LaneATT/lib/datasets/lane_dataset.py", line 274, in __getitem__
    line_strings_org = LineStringsOnImage(line_strings_org, shape=img_org.shape)
AttributeError: 'NoneType' object has no attribute 'shape'

python-BaseException

  0%|                                                    | 0/15 [03:49<?, ?it/s]
  0%|                                                 | 0/11110 [03:15<?, ?it/s]

Process finished with exit code 1

**Comment by lucastabelini** [comment]
Check if the dataset is set up correctly. OpenCV returns `None` when it tries to load an image but fails to do so. The image path is probably incorrect.

**Comment by daeunni** [comment]
@wangnian97  Hi, I have same problem with u. 
How did you solve it?

**Comment by 1823449** [comment]
请问解决了吗

**Comment by zhangzhongyuan1996** [comment]
解决了吗？

**Comment by zhangzhongyuan1996** [comment]
我也遇到这个问题了

**Comment by zhangzhongyuan1996** [comment]
> 

解决了吗兄弟？
