### ISSUE TITLE
NMS replacement

### ISSUE THREAD

**Issue by SJLNNU** [lucastabelini/LaneATT#94]
Hi, Thank you very much for your work!

There is one problem I want to ask about.

My CUDA11 seems didn't worked well with libs/nms . So I decided to change the nms to torchvision.ops.boxes.nms

But the shape of proposals is [1000,77],(was training os culane),but the torchvision.ops.boxes.nms require [N,4] for input shape. How can I change the proposals to fit the input of torchvision.ops.boxes.nms. 

Thanks a lot .

**Comment by lucastabelini** [comment]
The NMS procedure implemented in Torchvision is for bounding boxes. The one in this repository is for lane boundaries. The two are not interchangeable. To run LaneATT you will have to install the NMS module implemented in this repository. You should be able to install it on a system with CUDA 11.

**Comment by SJLNNU** [comment]
Thank you for the reply!

I tried build NMS module in the first place . There is my device and CUDA11 info.
![QQ截图20211227150414](https://user-images.githubusercontent.com/31751988/147444991-d8c3a729-245f-420f-b1ed-a8d07fd1f7e7.png)
![QQ截图20211227150312](https://user-images.githubusercontent.com/31751988/147444996-5e8ef084-dd89-4f07-93a0-71688f94554c.png)

But after I got this 
`(laneatt_test) njnu@njnu-System-Product-Name:~/Codes/Image_software/Lane/LaneATT/lib/nms$ python setup.py install
running install
running bdist_egg
running egg_info
writing src/nms.egg-info/PKG-INFO
writing dependency_links to src/nms.egg-info/dependency_links.txt
writing top-level names to src/nms.egg-info/top_level.txt
reading manifest file 'src/nms.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'nms.details' extension
Emitting ninja build file /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] :/usr/local/cuda-11.0/bin/nvcc -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/TH -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-11.0/include -I/home/njnu/anaconda3/envs/laneatt_test/include/python3.7m -c -c /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/src/nms_kernel.cu -o /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/src/nms_kernel.o
:/usr/local/cuda-11.0/bin/nvcc -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/TH -I/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-11.0/include -I/home/njnu/anaconda3/envs/laneatt_test/include/python3.7m -c -c /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/src/nms_kernel.cu -o /home/njnu/Codes/Image_software/Lane/LaneATT/lib/nms/build/temp.linux-x86_64-3.7/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/usr/local/cuda-11.0/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/njnu/anaconda3/envs/laneatt_test/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

I Checked The [NMS module](https://github.com/gdlg/pytorch_nms) , The author of NMS suggested using torchvision version.
So I Changed the libs/models/laneatt.py 
at line 9  ` from torchvision.ops.boxes import nms`
at line 129 and 130 to ` keep=nms(proposals[:,:4],scores,nms_thres)`  

Then I run the script `python main.py train --exp_name laneatt_culane_resnet122 --cfg cfgs/laneatt_culane_resnet122.yml`
Its now training and the loss number is similar to the training log of yours .
I dont know if I am doing the right change,please help me out .
Thanks again.

**Comment by SJLNNU** [comment]
I am closing this issue. Replace torchvision.ops.boxes.nms is not going to work. It has to install the nms module  like the author said. 
If anyone building nms module with CUDA11 and RTX3090 add  `export TORCH_CUDA_ARCH_LIST="8.0"` before you setup.
Thanks again.

**Comment by YyChen818** [comment]
Hi, I'm so sorry to bother you, but I got the same problem with you when I install the nms module. I just want to know that did you solve this problem and how. hope to receive your reply, Thanks.
