### ISSUE TITLE
nms is not callable

### ISSUE THREAD

**Issue by Aliweka2020** [lucastabelini/LaneATT#97]
I got this error while training 

Traceback (most recent call last):
  File "C:\Users\Ali\radwan\LaneATT-main\main.py", line 59, in <module>
    main()
  File "C:\Users\Ali\radwan\LaneATT-main\main.py", line 52, in main
    runner.train()
  File "C:\Users\Ali\radwan\LaneATT-main\lib\runner.py", line 51, in train
    outputs = model(images, **self.cfg.get_train_parameters())
  File "C:\Users\Ali\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Ali\radwan\LaneATT-main\lib\models\laneatt.py", line 108, in forward
    proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold)
  File "C:\Users\Ali\radwan\LaneATT-main\lib\models\laneatt.py", line 129, in nms
    keep, num_to_keep, _ = nms(proposals, scores, overlap=nms_thres, top_k=nms_topk)
TypeError: 'module' object is not callable

**Comment by lucastabelini** [comment]
Please see #18 and #25.

**Comment by gin564319329** [comment]
> I got this error while training
> 
> Traceback (most recent call last): File "C:\Users\Ali\radwan\LaneATT-main\main.py", line 59, in main() File "C:\Users\Ali\radwan\LaneATT-main\main.py", line 52, in main runner.train() File "C:\Users\Ali\radwan\LaneATT-main\lib\runner.py", line 51, in train outputs = model(images, **self.cfg.get_train_parameters()) File "C:\Users\Ali\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\Ali\radwan\LaneATT-main\lib\models\laneatt.py", line 108, in forward proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold) File "C:\Users\Ali\radwan\LaneATT-main\lib\models\laneatt.py", line 129, in nms keep, num_to_keep, _ = nms(proposals, scores, overlap=nms_thres, top_k=nms_topk) TypeError: 'module' object is not callable

How did you solve the problem
