### ISSUE TITLE
replace the nms code error 

### ISSUE THREAD

**Issue by hwang12345** [lucastabelini/LaneATT#99]
`
    def Lane_nms(self,proposals,scores,overlap=50, top_k=4):
        '''
        re-write lane-nms with python
        reference: https://arxiv.org/pdf/2010.12035.pdf
        '''
        keep_index = []
        sorted_score, indices = torch.sort(scores, descending=True) # from big to small 
        r_filters = np.zeros(len(scores))

        for i,indice in enumerate(indices):
            if r_filters[i]==1: # continue if this proposal is filted by nms before
                continue
            keep_index.append(indice)
            if len(keep_index)>top_k: # break if more than top_k
                break
            if i == (len(scores)-1):# break if indice is the last one
                break
            sub_indices = indices[i+1:]
            for sub_i,sub_indice in enumerate(sub_indices):
                r_filter = self.Lane_IOU(proposals[indice,:],proposals[sub_indice,:],overlap)
                if r_filter: r_filters[i+1+sub_i]=1 
        num_to_keep = len(keep_index)

    def Lane_IOU(self,parent_box, compared_box, threshold):
        '''
        calculate distance one pair of proposal lines
        return True if distance less than threshold 
        '''
        start_a = (parent_box[2] * self.n_strips + 0.5).int() # add 0.5 trick to make int() like round  
        start_b = (compared_box[2] * self.n_strips + 0.5).int()
        start = torch.max(start_a,start_b)
        end_a = start_a + parent_box[4] - 1 + 0.5 - (((parent_box[4] - 1)<0).int())
        end_b = start_b + compared_box[4] - 1 + 0.5 - (((compared_box[4] - 1)<0).int())
        end = torch.min(torch.min(end_a,end_b),torch.tensor(self.n_offsets-1))
        if (end - start)<0:
            return False
        dist = 0
        for i in range(5+start,77):
            if i>(5+end):
                break
            if parent_box[i] < compared_box[i]:
                dist += compared_box[i] - parent_box[i]
            else:
                dist += parent_box[i] - compared_box[i]
        return dist < (threshold * (end - start + 1))`

hey, @Lllllp93 i used you code replace the nms ,get some error.please help

(laneatt) hw@hw-desk:~/project/LaneDetection/lane-att$ python main.py train --exp_name laneatt_r18_tusimple --cfg cfgs/laneatt_tusimple_resnet18.yml 
[2022-02-10 10:12:19,014] [lib.datasets.tusimple] [INFO] Loading TuSimple annotations...
[2022-02-10 10:12:19,021] [lib.datasets.tusimple] [INFO] 270 annotations loaded, with a maximum of 1 lanes in an image.
[2022-02-10 10:12:19,021] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2022-02-10 10:12:19,102] [lib.datasets.lane_dataset] [INFO] Done.
  0%|                                                   | 0/100 [00:00<?, ?it/s15.0 None                                                 | 0/34 [00:00<?, ?it/s]
  0%|                                                   | 0/100 [00:01<?, ?it/s]
Traceback (most recent call last):                                              
  File "main.py", line 63, in <module>
    main()
  File "main.py", line 52, in main
    runner.train()
  File "/home/hw/project/LaneDetection/lane-att/lib/runner.py", line 59, in train
    outputs = model(images, **self.cfg.get_train_parameters())
  File "/home/hw/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hw/project/LaneDetection/lane-att/lib/models/laneatt.py", line 126, in forward
    proposals_list = self.nms(
  File "/home/hw/project/LaneDetection/lane-att/lib/models/laneatt.py", line 150, in nms
    keep, num_to_keep, _ = self.Lane_nms(
  File "/home/hw/project/LaneDetection/lane-att/lib/models/laneatt.py", line 180, in Lane_nms
    r_filter = self.Lane_IOU(proposals[indice, :], proposals[sub_indice, :], overlap)
  File "/home/hw/project/LaneDetection/lane-att/lib/models/laneatt.py", line 195, in Lane_IOU
    end = torch.min(torch.min(end_a, end_b), torch.tensor(self.n_offsets - 1))
RuntimeError: Expected object of scalar type float but got scalar type long int for argument 'other'

**Comment by lucastabelini** [comment]
Please move this discussion to the correct issue (#77) and stop creating unnecessary new ones.
